import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "The Coordinated Living",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preload" href="/coordinated.webp" as="image" type="image/webp" />
        <link rel="icon" href="/coordinated.ico" />
      </head>
      <body className={manrope.className}>{children}</body>
    </html>
  );
}
