import type { Metadata } from "next";
import { Manrope, Roboto } from "next/font/google";
import { Amita } from "next/font/google";
import "./globals.css";

const manrope = Manrope({ 
  subsets: ["latin"],
  display: 'swap'
});

const roboto = Roboto({ 
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  variable: "--font-roboto",
  display: 'swap'
});

const amita = Amita({ 
  subsets: ["latin"],
  weight: "400",
  variable: "--font-amita",
  display: 'swap'
});

export const metadata: Metadata = {
  title: "The Coordinated Living",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="preload" href="/coordinated.webp" as="image" type="image/webp" />
        <link rel="icon" href="/coordinated.ico" />
      </head>
      <body className={`${manrope.className} ${roboto.variable} ${amita.variable}`}>{children}</body>
    </html>
  );
}
