import React from 'react';

const FullTermsContent = () => {
  return (
    <>
      <h3 className="text-lg font-semibold text-white mt-6 mb-3">Table of Contents</h3>
      <ul className="list-disc list-inside space-y-1 ml-4">
        <li>Definitions</li>
        <li>Scope of Service</li>
        <li>Privacy Policy</li>
        <li>Children&apos;s Privacy</li>
        <li>Cookies</li>
        <li>License</li>
        <li>Hyperlinking to our Content</li>
        <li>Content Liability</li>
        <li>Reservation of Rights</li>
        <li>Prices</li>
        <li>Payment</li>
        <li>Correspondence and Communication</li>
        <li>Disclaimer</li>
        <li>Intellectual property rights</li>
        <li>Dispute Resolution</li>
        <li>Removal of links</li>
      </ul>
      
      <h3 className="text-lg font-semibold text-white mt-6 mb-3">1. DEFINITIONS</h3>
      <p>
        &quot;IKOORDINATE&quot;, &quot;we&quot;, &quot;us&quot;, &quot;our&quot;, &quot;the company&quot; means THE COORDINATE LIVING.
      </p>
      <p>
        &quot;IKOORDINATE&quot;, is the trade name for THE COORDINATE LIVING, a Sole Proprietorship registered under the laws of Ghana, and having its registered address at Number 26 Ntreh Street, Adenta- Greater Accra Region.
      </p>
      <p>
        The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
      </p>
      <p>
        For the purposes of this Privacy Policy:
      </p>
      <ul className="list-disc list-inside space-y-2 ml-4">
        <li><strong>&quot;Account&quot;</strong> means a unique account created for You to access our Service or parts of our Service.</li>
        <li><strong>&quot;Affiliate&quot;</strong> means an entity that controls, is controlled by or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
        <li><strong>&quot;Company&quot;</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to Ikoordinate, Accra, Ghana.</li>
        <li><strong>&quot;Cookies&quot;</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
        <li><strong>&quot;Country&quot;</strong> refers to: Ghana</li>
        <li><strong>&quot;Device&quot;</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
        <li><strong>&quot;Personal Data&quot;</strong> is any information that relates to an identified or identifiable individual.</li>
        <li><strong>&quot;Platform&quot;</strong> means the (mobile) website and apps on which the Service is made available, owned, controlled, managed, maintained and/or hosted by IKOORDINATE</li>
        <li><strong>&quot;Service&quot;</strong> means the online facility booking avenue (including the facilitation of payments) of various products and services made available by IKOORDINATE.</li>
        <li><strong>&quot;Service Provider&quot;</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
        <li><strong>&quot;Usage Data&quot;</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
        <li><strong>&quot;Website&quot;</strong> refers to The Coordinated Living, accessible from https://thecoordinatedliving.com/</li>
        <li><strong>&quot;You&quot;</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
      </ul>
      
      <h3 className="text-lg font-semibold text-white mt-6 mb-3">2. SCOPE OF SERVICE</h3>
      <p>
        IKOORDINATE and its agents and partners shall provide an online service through the Platform, on which visitors/individuals of the Platform and by subscribing to the website, you enter into a direct (legally binding) contractual relationship with IKOORDINATE.
      </p>
      <p>
        We would employ optimum use of reasonable skill and care in the provision of our service. We rely on information provided to us by other service providers in the provisions of our services. We therefore cannot guarantee that all information is accurate, complete or correct, nor can we be held liable for any such information, errors (whether patent or latent), any interruptions (whether due to any temporary and/or partial breakdown, repair, upgrade or maintenance of our Platform or otherwise).
      </p>
      <p>
        Our service is made available for personal and non-commercial use only. Therefore, you are not allowed to re-sell, deep-link, use, copy, monitor, display, download or reproduce any content or information, software, bookings, tickets, products or services available on our Platform for any commercial or competitive activity or purpose without our prior knowledge.
      </p>
      
      <h3 className="text-lg font-semibold text-white mt-6 mb-3">3. PRIVACY POLICY</h3>
      <p>
        IKOORDINATE respects your privacy and are committed to ensuring the safety of the information you provide us. In order to constantly improve upon the services that we provide you with, we may collect and use information which you provide to us.
      </p>
      <p>
        While using Our Service, we may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
      </p>
      <ul className="list-disc list-inside space-y-1 ml-4">
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Phone number</li>
        <li>Address, State, Province, ZIP/Postal code, City</li>
        <li>Usage Data</li>
      </ul>
      
      <p className="mt-4">
        The Company may use Personal Data for the following purposes:
      </p>
      <ul className="list-disc list-inside space-y-2 ml-4">
        <li><strong>To provide and maintain our Service:</strong> including to monitor the usage of our Service.</li>
        <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
        <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
        <li><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application&apos;s push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
        <li><strong>To provide you with news, special offers and general information:</strong> about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</li>
        <li><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
        <li><strong>For business transfers:</strong> We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</li>
        <li><strong>For other purposes:</strong> We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</li>
      </ul>
      
      <p className="mt-4">
        We may share Your personal information in the following situations:
      </p>
      <ul className="list-disc list-inside space-y-2 ml-4">
        <li><strong>With Service Providers:</strong> We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.</li>
        <li><strong>For business transfers:</strong> We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</li>
        <li><strong>With Affiliates:</strong> We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</li>
        <li><strong>With business partners:</strong> We may share Your information with Our business partners to offer You certain products, services or promotions.</li>
        <li><strong>With other users:</strong> when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.</li>
        <li><strong>With Your consent:</strong> We may disclose Your personal information for any other purpose with Your consent.</li>
      </ul>
      
      <h3 className="text-lg font-semibold text-white mt-6 mb-3">4. CHILDREN&apos;S PRIVACY</h3>
      <p>
        Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, we take steps to remove that information from Our servers.
      </p>
      <p>
        If we need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, we may require Your parent&apos;s consent before We collect and use that information.
      </p>
      <p>
        We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
      </p>
      <p>
        We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the &quot;Last updated&quot; date at the top of this Privacy Policy.
      </p>
      <p>
        You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page. If you have any questions about this Privacy Policy, you can contact us:
      </p>
      <p>
        By email: <a href="mailto:letstalk@thecoordinatedliving.com" className="underline font-bold text-white">letstalk@thecoordinatedliving.com</a>
      </p>
      
      <h3 className="text-lg font-semibold text-white mt-6 mb-3">5. COOKIES</h3>
      <p>
        Cookies are used for different purposes. They allow you to be recognized as the same user across the pages of a website, between websites or in your usage of an app. The types of information that we collect through cookies include IP address; device ID; viewed pages; browser type; browsing information; operating system; internet service provider; timestamp; responses to advertisements; the referring URL; and features used or activities engaged in within the website/apps.
      </p>
      <p>
        We employ the use of cookies. By accessing website, you agree to use cookies in agreement with the ikoordinate&apos;s Privacy Policy.
      </p>
      <p>
        Most interactive websites use cookies to let us retrieve the user&apos;s details for each visit. Cookies are used by our website to enable the functionality of certain areas to make it easier for people visiting our website. Some of our affiliate/advertising partners may also use cookies.
      </p>
      <p>
        Our website and apps use cookies for different purposes, these include;
      </p>
      
      <h4 className="text-md font-semibold text-white mt-4 mb-2">Tracking Technologies and Cookies</h4>
      <p>
        We endeavor to offer our visitors an advanced, user-friendly website and apps that adapt automatically to their needs and wishes. To achieve this, we use technical cookies to show you our website, to track the activity on our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.
      </p>
      <p>
        These technical cookies are absolutely necessary for our website to function properly. The technologies We use may include:
      </p>
      
      <h4 className="text-md font-semibold text-white mt-4 mb-2">Cookies or Browser Cookies</h4>
      <p>
        A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, you may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.
      </p>
      
      <h4 className="text-md font-semibold text-white mt-4 mb-2">Web Beacons</h4>
      <p>
        Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).
      </p>
      <p>
        Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.
      </p>
      <p>
        We use both Session and Persistent Cookies for the purposes set out below:
      </p>
      
      <h4 className="text-md font-semibold text-white mt-4 mb-2">Necessary / Essential Cookies</h4>
      <p>
        These are session Cookies administered by Ikoordinate and these Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.
      </p>
      
      <h4 className="text-md font-semibold text-white mt-4 mb-2">Cookies Policy / Notice Acceptance Cookies</h4>
      <p>
        These are Persistent Cookies that are administered by Us for the purposes of identifying if users have accepted the use of cookies on the Website.
      </p>
      
      <h4 className="text-md font-semibold text-white mt-4 mb-2">Functionality Cookies</h4>
      <p>
        We also use functional cookies to remember your preferences and to help you to use our website and apps efficiently and effectively. These functional cookies are not strictly necessary for the functioning of our website or apps, but they add functionality and enhance the services we provide you with.
      </p>
      <p>
        The purpose of these functional Cookies is to allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.
      </p>
      <p>
        For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the cookies section of our Privacy Policy
      </p>
      
      <h4 className="text-md font-semibold text-white mt-4 mb-2">Commercial cookies</h4>
      <p>
        We use third-party cookies as well as our own to display personalized advertisements on our websites and on other websites. This is called &quot;retargeting,&quot; and it is based on browsing activities, such as the destinations you have been searching for, the product you have viewed and the prices you have been shown.
      </p>
      
      <h3 className="text-lg font-semibold text-white mt-6 mb-3">6. LICENSE</h3>
      <p>
        Unless otherwise stated ikoordinate and/or its licensors own the intellectual property rights for all material on the website. All intellectual property rights are reserved. You may access this from The Coordinated Living for your own personal use subjected to restrictions set in these terms and conditions.
      </p>
      <p>
        You must not:
      </p>
      <ul className="list-disc list-inside space-y-1 ml-4">
        <li>Republish material from THE COORDINATE LIVING</li>
        <li>Sell, rent or sub-license material from THE COORDINATE LIVING</li>
        <li>Reproduce, duplicate or copy material from THE COORDINATE LIVING</li>
        <li>Redistribute content from THE COORDINATE LIVING</li>
      </ul>
      <p>
        Parts of this website offer an opportunity for users to post and exchange opinions and information in certain areas of the website. ikoordinate does not filter, edit, publish or review Comments prior to their presence on the website. Comments do not reflect the views and opinions of ikoordinate, its agents and/or affiliates. Comments reflect the views and opinions of the person who post their views and opinions. To the extent permitted by applicable laws, ikoordinate shall not be liable for the Comments or for any liability, damages or expenses caused and/or suffered as a result of any use of and/or posting of and/or appearance of the Comments on this website.
      </p>
      <p>
        ikoordinate reserves the right to monitor all Comments and to remove any Comments which can be considered inappropriate, offensive or causes breach of these Terms and Conditions.
      </p>
      <p>
        You warrant and represent that:
      </p>
      <ul className="list-disc list-inside space-y-1 ml-4">
        <li>You are entitled to post the Comments on our website and have all necessary licenses and consents to do so;</li>
        <li>The Comments do not invade any intellectual property right, including without limitation copyright, patent or trademark of any third party;</li>
        <li>The Comments do not contain any defamatory, libelous, offensive, indecent or otherwise unlawful material which is an invasion of privacy</li>
        <li>The Comments will not be used to solicit or promote business or custom or present commercial activities or unlawful activity.</li>
      </ul>
      <p>
        You hereby grant ikoordinate a non-exclusive license to use, reproduce, edit and authorize others to use, reproduce and edit any of your Comments in any and all forms, formats or media.
      </p>
      
      <h3 className="text-lg font-semibold text-white mt-6 mb-3">7. HYPERLINKING TO OUR CONTENT</h3>
      <p>
        The following organizations may link to our website without prior written approval:
      </p>
      <ul className="list-disc list-inside space-y-1 ml-4">
        <li>Government agencies;</li>
        <li>Search engines;</li>
        <li>News organizations;</li>
        <li>Online directory distributors may link to our website in the same manner as they hyperlink to the Websites of other listed businesses; and</li>
        <li>System wide Accredited Businesses except soliciting non-profit organizations, charity shopping malls, and charity fundraising groups which may not hyperlink to our Web site.</li>
      </ul>
      <p>
        These organizations may link to our home page, to publications or to other Website information so long as the link: (a) is not in any way deceptive; (b) does not falsely imply sponsorship, endorsement or approval of the linking party and its products and/or services; and (c) fits within the context of the linking party&apos;s site.
      </p>
      <p>
        We may consider and approve other link requests from the following types of organizations:
      </p>
      <ul className="list-disc list-inside space-y-1 ml-4">
        <li>commonly-known consumer and/or business information sources;</li>
        <li>dot.com community sites;</li>
        <li>associations or other groups representing charities;</li>
        <li>online directory distributors;</li>
        <li>internet portals;</li>
        <li>accounting, law and consulting firms; and</li>
        <li>educational institutions and trade associations.</li>
      </ul>
      <p>
        We will approve link requests from these organizations if we decide that: (a) the link would not make us look unfavorably to ourselves or to our accredited businesses; (b) the organization does not have any negative records with us; (c) the benefit to us from the visibility of the hyperlink compensates the absence of ikoordinate; and (d) the link is in the context of general resource information.
      </p>
      <p>
        These organizations may link to our home page so long as the link: (a) is not in any way deceptive; (b) does not falsely imply sponsorship, endorsement or approval of the linking party and its products or services; and (c) fits within the context of the linking party&apos;s site.
      </p>
      <p>
        If you are one of the organizations listed in paragraph 2 above and are interested in linking to our website, you must inform us by sending an e-mail to ikoordinate. Please include your name, your organization name, contact information as well as the URL of your site, a list of any URLs from which you intend to link to our website, and a list of the URLs on our site to which you would like to link. Wait 2-3 weeks for a response.
      </p>
      <p>
        Approved organizations may hyperlink to our website as follows:
      </p>
      <ul className="list-disc list-inside space-y-1 ml-4">
        <li>By use of our corporate name; or</li>
        <li>By use of the uniform resource locator being linked to; or</li>
        <li>By use of any other description of our website being linked to that makes sense within the context and format of content on the linking party&apos;s site.</li>
      </ul>
      <p>
        No use of ikoordinate&apos;s logo or other artwork will be allowed for linking absent a trademark license agreement.
      </p>
      
      <h3 className="text-lg font-semibold text-white mt-6 mb-3">8. CONTENT LIABILITY</h3>
      <p>
        We shall not be held responsible for any content that appears on your Website. You agree to protect and defend us against all claims that is rising on your Website. No link(s) should appear on any Website that may be interpreted as libelous, obscene or criminal, or which infringes, otherwise violates, or advocates the infringement or other violation of, any third-party rights.
      </p>
      
      <h3 className="text-lg font-semibold text-white mt-6 mb-3">9. RESERVATION OF RIGHTS</h3>
      <p>
        We reserve the right to request that you remove all links or any particular link to our website. You approve to immediately remove all links to our Website upon request. We also reserve the right to these terms and conditions and it&apos;s linking policy at any time. By continuously linking to our website, you agree to be bound to and follow these linking terms and conditions.
      </p>
      
      <h3 className="text-lg font-semibold text-white mt-6 mb-3">10. PRICES</h3>
      <p>
        The prices on our Platform are highly competitive. All our services are at a subscription fee including VAT/sales tax and all other taxes (subject to change of such taxes), unless stated otherwise on our Platforms or the confirmation email.
      </p>
      
      <h3 className="text-lg font-semibold text-white mt-6 mb-3">11. PAYMENT</h3>
      <p>
        If applicable and available, you may be required to make full or part-payment of subscription fee as required under the payment policy of website in question by means of secure online payment (all to the extent offered and supported by your bank). In some cases, mobile money payment may be allowed.
      </p>
      <p>
        There may be instances where payment is safely processed from your credit/debit card, bank account or mobile money account to our bank account through a third-party payment processor. Any payment facilitated by us will in each case constitute a payment of (part of) the website fee price by you of the relevant product or service in final settlement of such (partial) due and payable price and you cannot reclaim such paid monies.
      </p>
      <p>
        For certain (non-refundable) rates or special offers, please note that we may require that payment is made upfront by wire transfer (if available) or by credit card or mobile money, and therefore your credit card may be pre-authorized or charged (sometimes without any option for refund) upon paying for the site.
      </p>
      <p>
        If you wish to review, adjust or cancel your subscription, please revert to the confirmation email and follow the instructions therein. Please note depending on the particular subscription in question, you may either be charged for your cancellation, or forfeit any prepaid amount.
      </p>
      <p>
        If you have a late or delayed fees payment date, make sure to effectively communicate it to us to avoid cancellation of a subscription or renewal without prior notice.
      </p>
      
      <h3 className="text-lg font-semibold text-white mt-6 mb-3">12. CORRESPONDENCE AND COMMUNICATION</h3>
      <p>
        Ikoordinate shall communicate to prospective subscribers via one or more of the following means – SMS, Email, Phone Call, etc. Customers may also reach the company through our CONTACT US mediums during work hours.
      </p>
      <p>
        By subscribing, you agree to receive from us
      </p>
      <ul className="list-disc list-inside space-y-1 ml-4">
        <li>an email, SMS, phone call or any of our communication mediums as listed above, shortly after your successful subscription providing you with certain information relevant to the website.</li>
        <li>an email containing a receipt of your subscription fee. Please see our privacy and cookies policy for more information about how we may contact you</li>
      </ul>
      <p>
        In order to duly complete and secure your booking, you need to use your preferred and correct email address. We are not responsible or liable for (and have no obligation to verify) any wrong or misspelled email address or inaccurate or wrong (mobile) phone number or credit card number or mobile money number.
      </p>
      <p>
        Any claim or complaint against Ikoordinate or in respect of the service we provide must be promptly submitted via email, but in any event within thirty (30) days after the event giving rise to the complaint. Any claim or complaint that is submitted after the thirty (30) day period, may be rejected and the claimant shall forfeit its right to any damages, compensation or costs.
      </p>
      
      <h3 className="text-lg font-semibold text-white mt-6 mb-3">13. DISCLAIMER</h3>
      <p>
        To the maximum extent permitted by applicable law, we exclude all representations, warranties and conditions relating to our website and the use of this website. Nothing in this disclaimer will:
      </p>
      <ul className="list-disc list-inside space-y-1 ml-4">
        <li>limit or exclude our or your liability for death or personal injury;</li>
        <li>limit or exclude our or your liability for fraud or fraudulent misrepresentation;</li>
        <li>limit any of our or your liabilities in any way that is not permitted under applicable law; or</li>
        <li>exclude any of our or your liabilities that may not be excluded under applicable law.</li>
      </ul>
      <p>
        The limitations and prohibitions of liability set in this Section and elsewhere in this disclaimer: (a) are subject to the preceding paragraph; and (b) govern all liabilities arising under the disclaimer, including liabilities arising in contract, in tort and for breach of statutory duty.
      </p>
      <p>
        As long as the information and services on the website are provided we will not be liable for any loss or damage of any nature.
      </p>
      
      <h3 className="text-lg font-semibold text-white mt-6 mb-3">14. INTELLECTUAL PROPERTY RIGHTS</h3>
      <p>
        Unless stated otherwise, the software required for our services or available at or used by our Website/Platform and the intellectual property rights (including the copyrights) of the contents and information of and material on our Platform are owned by Ikoordinate, its suppliers or providers.
      </p>
      <p>
        Ikoordinate exclusively retains ownership of all rights, title and interest in and to all intellectual property rights of the Platform/website on which the service is made available. You are not entitled to copy, scrape, deep-link, etc. to publish, promote, market, integrate, use, combine or otherwise use the content or our brand without our express written permission. Any unlawful use or any of the aforementioned actions will constitute a material infringement of our intellectual property rights which will entitle us to sue.
      </p>
      
      <h3 className="text-lg font-semibold text-white mt-6 mb-3">15. GOVERNING LAW</h3>
      <p>
        To the extent permitted by law, these Terms and Conditions and the provision of our services shall be governed by and construed in accordance with the laws of the Republic of Ghana.
      </p>
      
      <h3 className="text-lg font-semibold text-white mt-6 mb-3">16. DISPUTE RESOLUTION</h3>
      <p>
        Any dispute arising out of these general terms and conditions and our services shall in the first instance be settled amicably through mediation, failing which such dispute shall be submitted to a Court of competent jurisdiction in Accra, Ghana.
      </p>
      
      <h3 className="text-lg font-semibold text-white mt-6 mb-3">17. REMOVAL OF LINKS FROM OUR WEBSITE</h3>
      <p>
        If you find any link on our website that is offensive for any reason, you are free to contact and inform us any moment. We will consider requests to remove links but we are not obligated to or so or to respond to you directly.
      </p>
      <p>
        We do not ensure that the information on this website is correct, we do not warrant its completeness or accuracy; nor do we promise to ensure that the website remains available or that the material on the website is kept up to date.
      </p>
    </>
  );
};

export default FullTermsContent;
